/****************************************************************************
 *  (c) Copyright 2007 Wi-Fi Alliance.  All Rights Reserved
 *
 *
 *  LICENSE
 *
 *  License is granted only to Wi-Fi Alliance members and designated
 *  contractors (“Authorized Licensees”).  Authorized Licensees are granted
 *  the non-exclusive, worldwide, limited right to use, copy, import, export
 *  and distribute this software:
 *  (i) solely for noncommercial applications and solely for testing Wi-Fi
 *  equipment; and
 *  (ii) solely for the purpose of embedding the software into Authorized
 *  Licensee’s proprietary equipment and software products for distribution to
 *  its customers under a license with at least the same restrictions as
 *  contained in this License, including, without limitation, the disclaimer of
 *  warranty and limitation of liability, below.  The distribution rights
 *  granted in clause
 *  (ii), above, include distribution to third party companies who will
 *  redistribute the Authorized Licensee’s product to their customers with or
 *  without such third party’s private label. Other than expressly granted
 *  herein, this License is not transferable or sublicensable, and it does not
 *  extend to and may not be used with non-Wi-Fi applications.  Wi-Fi Alliance
 *  reserves all rights not expressly granted herein. 
 * 
 *  Except as specifically set forth above, commercial derivative works of
 *  this software or applications that use the Wi-Fi scripts generated by this
 *  software are NOT AUTHORIZED without specific prior written permission from
 *  Wi-Fi Alliance.
 * 
 *  Non-Commercial derivative works of this software for internal use are
 *  authorized and are limited by the same restrictions; provided, however,
 *  that the Authorized Licensee shall provide Wi-Fi Alliance with a copy of
 *  such derivative works under a perpetual, payment-free license to use,
 *  modify, and distribute such derivative works for purposes of testing Wi-Fi
 *  equipment.
 * 
 *  Neither the name of the author nor "Wi-Fi Alliance" may be used to endorse
 *  or promote products that are derived from or that use this software without
 *  specific prior written permission from Wi-Fi Alliance.
 *
 *  THIS SOFTWARE IS PROVIDED BY WI-FI ALLIANCE "AS IS" AND ANY EXPRESS OR
 *  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE,
 *  ARE DISCLAIMED. IN NO EVENT SHALL WI-FI ALLIANCE BE LIABLE FOR ANY DIRECT,
 *  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *  (INCLUDING, BUT NOT LIMITED TO, THE COST OF PROCUREMENT OF SUBSTITUTE
 *  GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 *  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 *  STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE) ARISING IN ANY WAY OUT OF
 *  THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. ******************************************************************************
 */
 

#ifndef WFA_VER_H
#define WFA_VER_H

#define WFA_VERNAM_LEN      32
/*
 * Current version support baseline programs and upcoming programs:
 *     Voice Enterprise
 *     WMM-AC
 *     PMF
 *     TDLS
 *     VHT
 *     Passpoint release 1
 *
 *     Releases:
 *     3.2 -- This release includes PMF and TDLS support
 *     3.3.2
 *     3.3.3 -- add the argument "channel" to TDLS optional
 *     3.3.4 -- add the argument "type" and "peer" to set_uapsd for TDLS
 *     3.3.5 -- add the "wfaStaSetMacAddress()" to wfa_cmdproc.c 
 *     3.3.6 -- update all KeyMgmt options to support "sha256", "ft" etc.
 *              Add NeigReq and TransMgmtQuery Frame to "STA_SEND_FRAME"
 *              Remove Send_NeigReq command.
 *     3.3.7 -- Add "wpa2" to keyMgmt
 *     3.3.8 -- add "sta_set_radio" command for TDLS
 *     3.3.9 -- add "sta_set_rfeature" command for TDLS
 *              add "tdlsMode" to Preset Command
 *     3.3.10 - fix a few bug during TDLS PF 
 *     6.0.0 -- This release includes Wi-Fi Display support ( Base )
 *     6.0.1 -- PF#1 - based on CAPI version 6.0.1
 *     6.0.2 -- PF#2 - based on CAPI version 6.0.2
 *	   6.0.0-DISP-v0.3 -- PF#3 - based on CAPI version 6.0.2 	
 *	   6.0.0-DISP-v0.4 -- PF#4 - based on Test plan version 0.13 	
 *	   6.0.0-DISP-v0.5 -- PF#5 
 *	   6.0.0-DISP-v0.5 -- TBRE 
 *     8.0.0 -- This release includes all changes from VHT program.
 *              This includes IPv6 ping support needed for Passpoint
 */
#define WFA_SYSTEM_VER      "PCEDUT-SIGMA-8.0.0"     
                                 

#endif
