/****************************************************************************
 *  (c) Copyright 2007 Wi-Fi Alliance.  All Rights Reserved
 *
 *
 *  LICENSE
 *
 *  License is granted only to Wi-Fi Alliance members and designated
 *  contractors (“Authorized Licensees”).  Authorized Licensees are granted
 *  the non-exclusive, worldwide, limited right to use, copy, import, export
 *  and distribute this software:
 *  (i) solely for noncommercial applications and solely for testing Wi-Fi
 *  equipment; and
 *  (ii) solely for the purpose of embedding the software into Authorized
 *  Licensee’s proprietary equipment and software products for distribution to
 *  its customers under a license with at least the same restrictions as
 *  contained in this License, including, without limitation, the disclaimer of
 *  warranty and limitation of liability, below.  The distribution rights
 *  granted in clause
 *  (ii), above, include distribution to third party companies who will
 *  redistribute the Authorized Licensee’s product to their customers with or
 *  without such third party’s private label. Other than expressly granted
 *  herein, this License is not transferable or sublicensable, and it does not
 *  extend to and may not be used with non-Wi-Fi applications.  Wi-Fi Alliance
 *  reserves all rights not expressly granted herein. 
 * 
 *  Except as specifically set forth above, commercial derivative works of
 *  this software or applications that use the Wi-Fi scripts generated by this
 *  software are NOT AUTHORIZED without specific prior written permission from
 *  Wi-Fi Alliance.
 * 
 *  Non-Commercial derivative works of this software for internal use are
 *  authorized and are limited by the same restrictions; provided, however,
 *  that the Authorized Licensee shall provide Wi-Fi Alliance with a copy of
 *  such derivative works under a perpetual, payment-free license to use,
 *  modify, and distribute such derivative works for purposes of testing Wi-Fi
 *  equipment.
 * 
 *  Neither the name of the author nor "Wi-Fi Alliance" may be used to endorse
 *  or promote products that are derived from or that use this software without
 *  specific prior written permission from Wi-Fi Alliance.
 *
 *  THIS SOFTWARE IS PROVIDED BY WI-FI ALLIANCE "AS IS" AND ANY EXPRESS OR
 *  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE,
 *  ARE DISCLAIMED. IN NO EVENT SHALL WI-FI ALLIANCE BE LIABLE FOR ANY DIRECT,
 *  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *  (INCLUDING, BUT NOT LIMITED TO, THE COST OF PROCUREMENT OF SUBSTITUTE
 *  GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 *  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 *  STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE) ARISING IN ANY WAY OUT OF
 *  THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE
 ******************************************************************************
 */
 

#ifndef WFA_CA_RESP_H
#define WFA_CA_RESP_H

typedef int (*dutCommandRespFuncPtr)(BYTE *cmdBuf);

int caCmdNotDefinedYet(BYTE *cmdBuf);
int wfaStaVerifyIpConnectResp(BYTE *cmdBuf);
int wfaStaSetIpConfigResp(BYTE *cmdBuf);
int wfaStaIsConnectedResp(BYTE *cmdBuf);
int wfaStaGetIpConfigResp(BYTE *cmdBuf);
int wfaGetVersionResp(BYTE *cmdBuf);
int wfaStaGetInfoResp(BYTE *cmdBuf);
int wfaTrafficAgentConfigResp(BYTE *cmdBuf);
int wfaTrafficAgentSendResp(BYTE *cmdBuf);
int wfaTrafficAgentRecvStartResp(BYTE *cmdBuf);
int wfaTrafficAgentRecvStopResp(BYTE *cmdBuf);
int wfaTrafficAgentResetResp(BYTE *cmdBuf);
int wfaTrafficAgentPingStartResp(BYTE *cmdBuf);
int wfaTrafficAgentPingStopResp(BYTE *cmdBuf);
int wfaStaGetMacAddressResp(BYTE *cmdBuf);
int wfaStaGetBSSIDResp(BYTE *cmdBuf);
int wfaStaSetEncryptionResp(BYTE *cmdBuf);
int wfaStaSetEapTLSResp(BYTE *cmdBuf);
int wfaStaSetPSKResp(BYTE *cmdBuf);
int wfaStaSetEapTTLSResp(BYTE *cmdBuf);
int wfaStaSetEapSIMResp(BYTE *cmdBuf);
int wfaStaSetEapPEAPResp(BYTE *cmdBuf);
int wfaStaAssociateResp(BYTE *cmdBuf);
int wfaStaSetIBSSResp(BYTE *cmdBuf);
int wfaStaGetStatsResp(BYTE *cmdBuf);
int wfaDeviceGetInfoResp(BYTE *cmdBuf);
int wfaDeviceListIFResp(BYTE *cmdBuf);
int wfaStaDebugSetResp(BYTE *cmdBuf);
void wfaStaDebugHexDump(BYTE *cmdBuf);
int wfaStaSetModeResp(BYTE *cmdBuf);
int wfaStaUploadResp(BYTE *cmdBuf);
int wfaStaSetUAPSDResp(BYTE *cmdBuf);
int wfaStaSetModeResp(BYTE *cmdBuf);
int wfaStaSetWMMResp(BYTE *cmdBuf);
int wfaStaPresetParametersResp(BYTE *cmdBuf);
int wfaStaSetEapFASTResp(BYTE *cmdBuf);
int wfaStaSetEapAKAResp(BYTE * cmdBuf);
int wfaStaSetSystimeResp(BYTE * cmdBuf);

int wfaStaSet11nResp(BYTE * cmdBuf);
int wfaStaSetWirelessResp(BYTE * cmdBuf);
int wfaStaSendADDBAResp(BYTE * cmdBuf);
int wfaStaCoexMgmtResp(BYTE * cmdBuf);
int wfaStaRifsTestResp(BYTE * cmdBuf);
int wfaStaResetDefaultResp(BYTE * cmdBuf);
int wfaStaDisconnectResp(BYTE * cmdBuf);

int wfaStandardReturn(BYTE *cmdBuf);

int wfaStaGenericResp(BYTE *cmdBuf);
/* P2P */
int 	wfaStaGetP2pDevAddressResp(BYTE *cmdBuf);          
int 	wfaStaSetP2pResp(BYTE *cmdBuf);			
int 	wfaStaP2pConnectResp(BYTE *cmdBuf);
int 	wfaStaStartAutoGO(BYTE *cmdBuf);
int 	wfaStaP2pStartGrpFormResp(BYTE *cmdBuf);         
int 	wfaStaP2pDissolveResp(BYTE *cmdBuf);            
int 	wfaStaSendP2pInvReqResp(BYTE *cmdBuf);		
int 	wfaStaAcceptP2pInvReqResp(BYTE *cmdBuf);		
int 	wfaStaSendP2pProvDisReqResp(BYTE *cmdBuf);     
int 	wfaStaSetWpsPbcResp(BYTE *cmdBuf); 
int 	wfaStaWpsReadPinResp(BYTE *cmdBuf);      
int 	wfaStaWpsEnterPinResp(BYTE *cmdBuf);		
int 	wfaStaGetPskResp(BYTE *cmdBuf);      
int 	wfaStaP2pResetResp(BYTE *cmdBuf);    
int 	wfaStaWpsReadLabelResp(BYTE *cmdBuf);
int 	wfaStaGetP2pIpConfigResp(BYTE *cmdBuf);
int 	wfaStaSendServiceDiscoveryReqResp(BYTE *cmdBuf);
int 	wfaStaSendP2pPresenceReqResp(BYTE *cmdBuf);
int 	wfaStaSetSleepReqResp(BYTE *cmdBuf);
int 	wfaStaSetOpportunisticPsReqResp(BYTE *cmdBuf);
int     wfaStaAddArpTableEntryResp(BYTE * cmdBuf);
int     wfaStaBlockICMPResponseResp(BYTE * cmdBuf);
/* P2P */
int     wfaStaStartWfdConnectionResp(BYTE * cmdBuf);
int		wfaStaCliCmdResp(BYTE * cmdBuf);
int		wfaStaConnectGoStartWfdResp(BYTE * cmdBuf);
int		wfaStaGenericResp(BYTE * cmdBuf);
int     wfaStaGetParameterResp(BYTE * cmdBuf);


#endif
