#!/bin/sh -e
#
 ############################################################################
 #  (c) Copyright 2007 Wi-Fi Alliance.  All Rights Reserved

 #  Author - Ankur Vachhani (avachhani@wi-fi.org) 
 #
 #  LICENSE
 #
 # License is granted only to Wi-Fi Alliance members and designated
 # contractors (“Authorized Licensees”).  Authorized Licensees are granted
 # the non-exclusive, worldwide, limited right to use, copy, import, export
 # and distribute this software:
 # (i) solely for noncommercial applications and solely for testing Wi-Fi
 # equipment; and
 # (ii) solely for the purpose of embedding the software into Authorized
 # Licensee’s proprietary equipment and software products for distribution to
 # its customers under a license with at least the same restrictions as
 # contained in this License, including, without limitation, the disclaimer of
 # warranty and limitation of liability, below.  The distribution rights
 # granted in clause (ii), above, include distribution to third party 
 # companies who will redistribute the Authorized Licensee’s product to their 
 # customers with or without such third party’s private label. Other than 
 # expressly granted herein, this License is not transferable or sublicensable,
 # and it does not extend to and may not be used with non-Wi-Fi applications. 
 # Wi-Fi Alliance reserves all rights not expressly granted herein. 
 # 
 # Except as specifically set forth above, commercial derivative works of
 # this software or applications that use the Wi-Fi scripts generated by this
 # software are NOT AUTHORIZED without specific prior written permission from
 # Wi-Fi Alliance. Non-Commercial derivative works of this software for 
 # internal use are authorized and are limited by the same restrictions; 
 # provided, however, that the Authorized Licensee shall provide Wi-Fi Alliance
 # with a copy of such derivative works under a perpetual, payment-free license
 # to use, modify, and distribute such derivative works for purposes of testing
 # Wi-Fi equipment.
 # Neither the name of the author nor "Wi-Fi Alliance" may be used to endorse
 # or promote products that are derived from or that use this software without
 # specific prior written permission from Wi-Fi Alliance.
 #
 # THIS SOFTWARE IS PROVIDED BY WI-FI ALLIANCE "AS IS" AND ANY EXPRESS OR
 # IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 # OF MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE,
 # ARE DISCLAIMED. IN NO EVENT SHALL WI-FI ALLIANCE BE LIABLE FOR ANY DIRECT,
 # INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 # (INCLUDING, BUT NOT LIMITED TO, THE COST OF PROCUREMENT OF SUBSTITUTE
 # GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 # HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 # STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE) ARISING IN ANY WAY OUT OF
 # THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
 # ############################################################################
 #

 #  File: SigmaWTGService.sh - The script to control Sigma WTG Service
 #	 This Service start PC-Endpoint and all the required control agents(for Testbed STAs)
 # 	 based on the configuration file - SigmaWTG.conf
 #
 #  Revision History:
 #        2008/08/15  -- Initially created by Ankur Vachhani
 #        


#CONF_FILE=/etc/SigmaWTG.conf
SERVICE=/usr/bin/startPCE_VE.sh

case "$1" in
    start)
        echo "Starting Sigma WTG Service for Voice"
#	$SERVICE 2>&1 >/dev/null&
	$SERVICE 2>&1 &
        ;;
    restart|reload|force-reload)
        echo "Stopping Sigma WTG Service for Voice "
	/usr/bin/killall -9 $SERVICE wfa_dut wfa_ca >/dev/null 2>&1
        echo "Starting Sigma WTG Service for Voice"
	$SERVICE >/dev/null 2>&1 &
        exit 3
        ;;
    stop)
        echo "Stopping Sigma WTG Service"
	/usr/bin/killall -9 $SERVICE wfa_dut wfa_ca >/dev/null 2>&1
        ;;
    *)
    	# This case is called by /etc/init.d/rc.local on system bootup
        echo "Starting Sigma WTG Service...for Voice"
	$SERVICE >/dev/null 2>&1 &
        exit 0
        ;;
esac

exit 0
